//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DollarTracker.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class Collaborator
    {
        public System.Guid CollaboratorId { get; set; }
        public string UserId { get; set; }
        public string ExpenseStoryId { get; set; }
        public System.DateTime CreatedUtcDt { get; set; }
        public bool Status { get; set; }
    }
}
