//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DollarTracker.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class CustomExpenseCategory
    {
        public CustomExpenseCategory()
        {
            this.Expense = new HashSet<Expense>();
        }
    
        public string CustomExpenseCategoryId { get; set; }
        public string UserId { get; set; }
        public string Description { get; set; }
        public Nullable<System.DateTime> CreatedDt { get; set; }
        public bool Status { get; set; }
    
        public virtual User User { get; set; }
        public virtual ICollection<Expense> Expense { get; set; }
    }
}
