//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DollarTracker.EF
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Common;
    
    public partial class DollarTrackerEntities : DbContext
    {
        public DollarTrackerEntities(string nameOrConnectionString)
            : base(nameOrConnectionString)
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
    	public DollarTrackerEntities(DbConnection connection) 
            : base(connection, true)
        {
        }
    
        public virtual DbSet<Collaborators> Collaborators { get; set; }
        public virtual DbSet<CustomExpenseCategories> CustomExpenseCategories { get; set; }
        public virtual DbSet<ExpenseCategories> ExpenseCategories { get; set; }
        public virtual DbSet<Expenses> Expenses { get; set; }
        public virtual DbSet<ExpenseStories> ExpenseStories { get; set; }
        public virtual DbSet<ExpenseStoryTypes> ExpenseStoryTypes { get; set; }
        public virtual DbSet<Users> Users { get; set; }
    }
}
