//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DollarTracker.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class ExpenseStoryType
    {
        public ExpenseStoryType()
        {
            this.ExpenseStory = new HashSet<ExpenseStory>();
        }
    
        public System.Guid ExpenseStoryTypeId { get; set; }
        public string Description { get; set; }
    
        public virtual ICollection<ExpenseStory> ExpenseStory { get; set; }
    }
}
