//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DollarTracker.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class ExpenseStory
    {
        public ExpenseStory()
        {
            this.Collaborator = new HashSet<Collaborator>();
            this.Expense = new HashSet<Expense>();
        }
    
        public string ExpenseStoryId { get; set; }
        public string ExpenseStoryTypeId { get; set; }
        public string Title { get; set; }
        public Nullable<float> Budget { get; set; }
        public Nullable<float> Income { get; set; }
        public string CreatedBy { get; set; }
        public System.DateTime StartDt { get; set; }
        public System.DateTime EndDt { get; set; }
        public System.DateTime CreatedUtcDt { get; set; }
    
        public virtual ICollection<Collaborator> Collaborator { get; set; }
        public virtual ICollection<Expense> Expense { get; set; }
        public virtual ExpenseStoryType ExpenseStoryType { get; set; }
    }
}
