//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DollarTracker.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class ExpenseStoryTypes
    {
        public ExpenseStoryTypes()
        {
            this.ExpenseStories = new HashSet<ExpenseStories>();
        }
    
        public System.Guid ExpenseStoryTypeId { get; set; }
        public string Description { get; set; }
    
        public virtual ICollection<ExpenseStories> ExpenseStories { get; set; }
    }
}
