//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DollarTracker.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class Users
    {
        public Users()
        {
            this.CustomExpenseCategories = new HashSet<CustomExpenseCategories>();
        }
    
        public System.Guid UserId { get; set; }
        public string Username { get; set; }
        public string Password { get; set; }
        public System.Guid PasswordSalt { get; set; }
        public string Email { get; set; }
        public System.DateTime CreatedDtUtc { get; set; }
        public bool Status { get; set; }
    
        public virtual ICollection<CustomExpenseCategories> CustomExpenseCategories { get; set; }
    }
}
