//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DollarTracker.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class User
    {
        public User()
        {
            this.CustomExpenseCategory = new HashSet<CustomExpenseCategory>();
        }
    
        public string UserId { get; set; }
        public string Username { get; set; }
        public string Email { get; set; }
        public System.DateTime CreatedDtUtc { get; set; }
        public bool Status { get; set; }
        public string DisplayName { get; set; }
    
        public virtual ICollection<CustomExpenseCategory> CustomExpenseCategory { get; set; }
    }
}
